config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :inventories
  # get 'home/index'
  get 'home/new_inventory'
  root 'home#index' 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory.rb
class Inventory < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :inventories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def addproduct
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1 or /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    # @inventory = Inventory.new
    @inventory = current_user.inventories.build

  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories or /inventories.json
  def create
    # @inventory = Inventory.new(inventory_params)
    @inventory = current_user.inventories.build(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventory_url(@inventory), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventory_url(@inventory), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @inventory = current_user.inventories.find_by(id: params[:id])
    redirect_to inventories_path, notice: "Not authorized to edit this product" if @inventory.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])

    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:product_name, :price, :quantity, :category, :vendor, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
  <%= link_to 'INVENTORY WEBAPP', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Inventory", inventories_path, class: "nav-link" %> 
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "Add Product", new_inventory_path, class: "nav-link" %>         
          </li>
          <li class="nav-item">
          <%= link_to "Sign Out",  destroy_user_session_path, method: :delete, class: "nav-link" %> 
          </li>
          <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %> 
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %> 
          </li>
          <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %> 
          </li>
        <% end %>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/addproduct.html.erb
<h1>Add product</h1>

app/views/home/index.html.erb
<h1>Home page</h1>

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "field form-group">
    <%= form.label :product_name, style: "display: block" %>
    <%= form.text_field :product_name, class:"form-control" %>
  </div>

  <div class= "field form-group">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, class:"form-control" %>
  </div>

  <div class= "field form-group">
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity, class:"form-control" %>
  </div>

  <div class= "field form-group">
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type, class:"form-control" %>
  </div>

  <div class= "field form-group">
    <%= form.label :vendor, style: "display: block" %>
    <%= form.text_field :vendor, class:"form-control" %>
  </div>

  <div class= "field form-group">
    <%= form.number_field :user_id, id: :inventory_user_id, class:"form-control", value: current_user.id, type: :hidden  %>
  </div>

          <br>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/inventories/_inventory.html.erb
<div id="<%= dom_id inventory %>">
  <p>
    <strong>Product name:</strong>
    <%= inventory.product_name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= inventory.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= inventory.quantity %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= inventory.type %>
  </p>

  <p>
    <strong>Vendor:</strong>
    <%= inventory.vendor %>
  </p>

</div>

app/views/inventories/edit.html.erb
<h1>Editing Product</h1>
<br/>
<%= render 'form', inventory: @inventory %>

<br/>
<%= link_to 'Show this inventory', @inventory, class:"btn btn-secondary" %>
<%= link_to 'Delete', @inventory, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<%= link_to 'Back', inventories_path, class:"btn btn-dark" %>

app/views/inventories/index.html.erb
<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr class="table-success">
      <th>Product Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Type</th>
      <th>Vendor</th>
      <th>User Id</th>
      <th></th>
      
    </tr>
  </thead>  
  
  <br>

  <tbody class="table-group-divider">

    <% @inventories.each do |inventory| %>  
      <% if inventory.user == current_user %>
        <tr>
          <td><%= inventory.product_name %></td>
          <td><%= inventory.price %></td>
          <td><%= inventory.quantity %></td>
          <td><%= inventory.type%></td>
          <td><%= inventory.vendor %></td>
          <td><%= inventory.user_id %></td>
          
          <td><%= link_to 'Show', inventory, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>        
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_inventory_path, class:"btn btn-secondary" %>

app/views/inventories/new.html.erb
<h1>New Product</h1>

<%= render "form", inventory: @inventory %>
<br>

<div>
  <%= link_to "Back", inventories_path, class:"btn btn-dark" %>
</div>

app/views/inventories/show.html.erb
<%= render @inventory %>
<div>
  <%= link_to "Edit", edit_inventory_path(@inventory), class:"btn btn-secondary" %> 
  <%= link_to "Back to Inventories", inventories_path, class: "btn btn-dark" %>
  <br>
  <br>
  <%= button_to "Delete", @inventory, method: :delete, class:"btn btn-danger btn-sm" %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>  
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Inventorywebapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  </head>

  <body>

  <%= render 'home/header' %>
  <div class="container">
  <br/>
  <% if notice %>
    <%= render 'layouts/alerts' %>
  <% end %>
  
    <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

  </body>
</html>